language: c++
env:
  global:
  - IDE_VERSION=1.8.1
  - BOARD="MightyCore:avr:1284:pinout=standard,variant=modelP,LTO=Os,clock=8MHz_internal"
  - SKETCH="HB-RC-12-EP.ino"
before_install:
- wget http://downloads.arduino.cc/arduino-$IDE_VERSION-linux64.tar.xz
- tar xf arduino-$IDE_VERSION-linux64.tar.xz
- mv arduino-$IDE_VERSION $HOME/arduino-ide
- export PATH=$PATH:$HOME/arduino-ide
install:
- mkdir -p $HOME/Arduino/libraries
- ln -s $PWD $HOME/Arduino/libraries/.
- arduino --pref "update.check=false" --save-prefs
- arduino --pref "boardsmanager.additional.urls=https://mcudude.github.io/MightyCore/package_MCUdude_MightyCore_index.json"
  --save-prefs
- arduino --install-boards MightyCore:avr:2.0.4
- git clone --branch=master https://github.com/pa-pa/AskSinPP.git $HOME/arduino-ide/libraries/AskSinPP
- git clone https://github.com/GreyGnome/EnableInterrupt $HOME/arduino-ide/libraries/EnableInterrupt
- git clone https://github.com/rocketscream/Low-Power.git $HOME/arduino-ide/libraries/Low-Power
- git clone https://github.com/adafruit/Adafruit-GFX-Library.git $HOME/arduino-ide/libraries/Adafruit-GFX-Library
- git clone https://github.com/olikraus/U8g2_for_Adafruit_GFX.git $HOME/arduino-ide/libraries/U8g2_for_Adafruit_GFX
- git clone https://github.com/ZinggJM/GxEPD.git $HOME/arduino-ide/libraries/GxEPD
script:
- arduino --verify --board $BOARD $PWD/$SKETCH
notifications:
  pushover:
    on_success: always
    on_failure: always
    api_key:
      secure: dy9KGxGQawhHlYqrYaA50MLIQRjLZcurIs8q/NI8NpCWZw9Do9oWeo7Do1fTc6l2IRCb9z/TxzslK4gJXJ5Tw+LX5K1PpUZsJ1OSexmSTIzfOSAjFWATmrBuhMl4rN0UfzlYVwuByIQJdpHEFbRnD84gri068EZDtswYRMtC754SEKSDBvnuWuzktRxoPBHN9EUYq24l8Zmbp30Bx/hcHblw+xCjQd+LMFLaDHc8wDozIJNQEZIhEC877aBSRUtYhDaZ9UiPmFaWwLNduq1fflygfrXIVXRS8Z3qC8F6qYis4pzaxyHxpmU//hD91XNrbQwRDNxvRJLYyzBB0X/ec9/T+caD2KkKUKOJrlMkoFjzKu+n/A7ik9MZz8HD8japbt/CYnsj6h8BzXPLUxOcUpSdu0L4MVBbxo6459knwEwOsFcR/28M5jXAHJU/LfzPDdkJwXZfvwHyg+McPtv+jVfjDUk85oafmEdhYG7Vl41DlRy/bpBxClv3uWPUT7PnLV+6+6zCpULqVSWwunB2EVsj2SwdRwNwmZiD4TKEuJdOxMJY71D9mJEGf4PU09GCE+EkyALv94HnfY1GwKpmDCEuWDs3wLU0Mn+0vt/OV4OAcUr5Vrd7/Tra2hgiViCVEYD6T8ZyvUq+Sio4FDw/vMk9g1ZgsUGbfFaENlO/2nM=
    users:
    - secure: NqnRrY3rzHPJduaoYvf+SBKM1gXlwtTBWCysa7KsezYs7Q6UgPjzgnpdwXIkJ6F0hnHMldMkZUty+a3Kb7eCQdcbHwY1dAEXe66HOrSLMTTldQJU+73qsl39UG1HM4B9dwq5vMSNcsRi/adcirWjilbIhTDWEci03Tj/e1YiGI4v5xHQgoyXk5QBQ6DZ6pKi3DxKXvrQpqwRgw508486UZkxT+MI2U1KyQmLszlM6ssvr0rBn1/Y7fJES1RKDuFCUv3YV240yMgv3EwgxSelQnA5/l7z5Rs4itdxVkHEParSiqa9GkNTsJjW3cKTVtp5LHSmRuovUKtJSHrfYiHWg9U6UhJkVaH4ub6XFLoQxxpszrGMOaFGI38vqk0cVv6oU7vnqizF8onXbcJNbFu9xnXClfbIZVd9mjX6mJXgi4gB/unqObVY0S/glddlrl7yJeIkoRoqpzZUOYqQfe+Nn/c6QU9Abdg6VX4gZ4I4ZXq5/6yjtBzMg51xrrxBgPQnCz4osu3pa+BPFxK17+NqVQl1oSM768yjCGUeSGCm7HuPTsVjsQhdn8pBGMwylt1my2y8wG4rb6+V7+WT3DGRQ2kCQeQopfdawsmbIbO7tTuwfE9JeS7uiJdNyt4FY9kH11mL483nSggNjIjDZSHbHEYz/UdV7DhwzcwsnUBSk7c=
  email:
    on_failure: always
