language: c++
env:
  global:
  - IDE_VERSION=1.8.1
  - BOARD="MightyCore:avr:1284:pinout=standard,variant=modelP,LTO=Os,clock=8MHz_internal"
  - SKETCH="HB-RC-12-EP.ino"
before_install:
- wget http://downloads.arduino.cc/arduino-$IDE_VERSION-linux64.tar.xz
- tar xf arduino-$IDE_VERSION-linux64.tar.xz
- mv arduino-$IDE_VERSION $HOME/arduino-ide
- export PATH=$PATH:$HOME/arduino-ide
install:
- mkdir -p $HOME/Arduino/libraries
- ln -s $PWD $HOME/Arduino/libraries/.
- arduino --pref "update.check=false" --save-prefs
- arduino --pref "boardsmanager.additional.urls=https://mcudude.github.io/MightyCore/package_MCUdude_MightyCore_index.json"
  --save-prefs
- arduino --install-boards MightyCore:avr:2.0.4
- git clone --branch=master https://github.com/pa-pa/AskSinPP.git $HOME/arduino-ide/libraries/AskSinPP
- git clone https://github.com/GreyGnome/EnableInterrupt $HOME/arduino-ide/libraries/EnableInterrupt
- git clone https://github.com/rocketscream/Low-Power.git $HOME/arduino-ide/libraries/Low-Power
- git clone https://github.com/adafruit/Adafruit-GFX-Library.git $HOME/arduino-ide/libraries/Adafruit-GFX-Library
- git clone https://github.com/olikraus/U8g2_for_Adafruit_GFX.git $HOME/arduino-ide/libraries/U8g2_for_Adafruit_GFX
- git clone https://github.com/ZinggJM/GxEPD.git $HOME/arduino-ide/libraries/GxEPD
script:
- arduino --verify --board $BOARD $PWD/$SKETCH
notifications:
  pushover:
    on_success: always
    on_failure: always
    api_key:
      secure: Gld4pP4W5H8SyJ29HOksBP2RhiUoUbwNFO2HhxhJNSFKFCgxthPOXtmVQCjOUipFcHafG3uYf1HygnkJps2QR1IosylK72GxP0u87NwIj5H+39tY+NO8yOPBLRCDC/YdtVVXb8wLx5Lbdg8g2e55colohC7M/x/9aeFElRyRvDPAodpQ4O0O8b60a5AQO+LV6Tn+aWGPDUUUD0oJj4zfMO4dzqLcW/glnL6gSQIspm9mQNXISWdSrV3B0yumxdhqmZEm4lHnRsmYi/mlPMXco7t4SqgQUxSHIWncN7R4VUDrLVXTzp9uGjKQGJyBj3Id0mxBGMXY29rmtr6rPofmDs4CFgj0alfEK5JIGWjQPf+xGZmbz5PV9OIvKEDQ6laLX2MMH5JEH4cCHdl9Jnj2sxKa9OeJTDNzTMkvkeYzOj+aRzXNHurUSgK9A3v/JcGUnsFEpLYESHVKxFMxdkMa7JeMrANc143a3oRN4/vwFvugr6RHBLuBuX171sJbrhPu8PH5AF9/vZo0OCUN2JIsPvm/+oE7I0JPknYAeDbdQrnqApTbcemy47bx2iRIstTam5jDWJ4g9S+srM2iZd7fKW+w/Bq7vCMFhP31ENELSezllUmej31dbgxwmotbLsg0uUZwCp2FN3g2PkgK56EBfW6t0rUkPr844FILHsTPn/g=
    users:
    - secure: LJo81atU2AI+YPy1gQdqaQ8jBkas4DYQxpN8foWkfKgHyq+FGWJ4ivD2sDxffvxeYQjxmVwmZef3Q68CvqLMLxwu/0lK9wn3I+rvMyRyl4RRKqZwjmad9ZzZisC0gxHgak8LUCQCuqZhV+qvBQNFAugqMZaxx4jkRiIw9AlcIXudo/j+7rvLMxC+tVAsYOJoaiyvaPQsDHumIRXno1LpASUeVq0hCym2s+F5Qof/NKKNkOpwPl17U2fmooX4wcWVrzvt2QzuZdd4DSUZOpmTFUWgB6tOHMft80psZ4bV+/HMydiIqD8vfoFzsMYThAtdqVY0LBd3bTsyjrMPgrhEqtvwC2RLKFolLMy0p9n7IS17iwepJ0mVjBTaiPZ1C0ZeCacombK87orrfbMiUcP+//OgNkIZRt/awgLmnTWE4smMabR3i8CSToWT0JDdJ1R3tehOxAfnxpRru5F8NPjj84+QqI0NOHlE7rREcvjUUZkPyNF8FMsD1zuUEPikS+dTuHZeuxqpGNaSz1E3gpLeG8WgjgSTKSECFBKe8ioMFsN/7uwAHF5V8a3fhFa/mvssqSrCZx/7EbVRP/RuuzxJSVHWsJlxSxEXgY1Zlrgh6NRrrMKBrqB5TV1FR5PaEfDWl5UICOBCiDM3cvTLJCctyNJS6PwG8DRlyiHnokICs88=
  email:
    on_failure: always
